### ISSUE TITLE
IN: Board integration

### ISSUE THREAD

**Issue by aeciorc** [hatchways/team-vanilla-bean#17]
- After signing up, user should see the dialog for creating a new board. If user comes back to the app later on and still hasn’t created a board, same thing happens
- Once they have created the board, it should become visible, rather than the mock data
- The title of the board should be visible on the blue bar

**Comment by milkcanbass** [comment]
This task include blueNav which displays board name.
here is copy from conversation we have about blue nav
 2 requests here
- on create post
- on dashboard get name
