### ISSUE TITLE
FE IN: New column

### ISSUE THREAD

**Issue by aeciorc** [hatchways/team-vanilla-bean#18]
- Hovering the left or right side of the board will display a button that you can click to add a new column on that position. 

--moved the task below  #38--
- Clicking on “Add a new card“ should create an empty card. You can give It a title and description and hit enter to save it.

**Comment by milkcanbass** [comment]
Since Zeinab working on Adding card function,
I moved the task below to  FEIN: Creating Card #38
> Clicking on “Add a new card“ should create an empty card. You can give It a title and description and hit enter to save it.

**Comment by milkcanbass** [comment]
finished implementation. Please check branch FEBE-dashBoard
-I set the area right side 
-To indicate where the user needs to move the cursor to create a column, I set the opacity of the place to 0.3. The opacity becomes 1 when the user puts the cursor on. The number becomes 1.
- the modal opens by clicking
- FE and BE is integrated



![Screen Shot 2020-02-25 at 4 12 24 PM](https://user-images.githubusercontent.com/38660310/75288476-6ebc0100-57ea-11ea-9c9a-5a259992233a.png)
